config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'users#index'
  
  resources :users, only: [:index]
  get '/users/:id/posts/new', to: 'posts#new'
  resources :users, only: [:show] do
    resources :posts, only: [:index, :show]
  end
  post '/users/:id/posts/create', to: 'posts#create'
  get '/users/:id/posts/:post_id/comments/new', to: 'comments#new'
  post '/users/:id/posts/:post_id/comments/create', to: 'comments#create'
  post '/users/:id/posts/:post_id/likes/create', to: 'likes#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_post_counter

  private

  def update_post_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_post_like_counter

  private

  def update_post_like_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  after_save :update_posts_count

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_count
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
# Include default devise modules. Others available are:
class User < ApplicationRecord
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def recent_three
    posts.order(created_at: :desc).limit(3)
  end

  def active_for_authentication?
    super && !confirmed_at.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to users_path
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = Like.new
    @like.author_id = current_user.id
    @like.post_id = params[:post_id]

    if @like.save
      redirect_to(request.referrer || root_path)
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_id = params[:user_id]
    @user = User.find(@user_id)
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user_id = params[:user_id]
    @post_id = params[:id]
    @post = User.find(@user_id).posts.find(@post_id)
    @user_name = User.find(@user_id).name
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.likes_counter = 0
    @post.comments_counter = 0

    if @post.save
      p 'PASSED', @post
      redirect_to user_post_path(current_user)
    else
      p 'FAILED', @post
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user_id = params[:id]
    @user = User.find(@user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= form_with model: @comment, url: "/users/id/posts/#{params[:post_id]}/comments/create" do |f|%>
  <div>
    <%= f.label :text, 'Comment' %>
    <%= f.text_field :text %>
  </div>
  <br/>
  <%= f.submit "Add Comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogiverse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_post_card.html.erb
<div class="post-card">
  <h3>Post #<%=index+1%>: <%=post.title%></h3>
  <p>
    <%= post.text.slice(0, 200)... %>
  </p>
  <h4>Comments: <%=post.comments_counter%>, Likes: <%=post.likes_counter%></h4>
</div>

app/views/posts/index.html.erb
<section class="user-profile">
  <div class="user-card">
    <img src=<%=@user.photo%> alt="user-profile" />
    <div class="card-info">
      <h2><%=@user.name%></h2>
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <div class="user-posts-container">
    <% @posts.each_with_index do |post, index| %>
      <div class="user-post">
        <%= link_to user_post_path(@user, post) do %>
          <%= render "post_card", index: index, post: post %>
        <% end %> 
        <div class="comments-container">
          <%if post.comments.empty? %>
            <p>No comments found!</p>
          <% else %>
            <% post.recent_comments.each do |comment| %>
              <p><%=@user.name%>: <%=comment.text%></p>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
    <button class="pagination">Pagination Placeholder</button>
  </div>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>

<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |message| %>
    <p><%= message %><p>
  <% end %>
<% end %>
<%= form_with url: "/users/21/posts/create", model: @post do |form|%>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>
  <%= form.submit "Add Post" %>
<%end%>

app/views/posts/show.html.erb
<section class="single-post">
  <div class="user-post">
    <div class="post-card relative">
      <h3>Post #<%=@post.id%>: <%=@post.title%></h3>
      <p>Author: <%=@user_name%></p>
      <h5>Comments: <%=@post.comments_counter%>, Likes: <%=@post.likes_counter%></h5>
      <p><%=@post.text%></p>
    </div>
    <div>
      <%= form_with model: @like , url: "/users/#{params[:id]}/posts/#{params[:id]}/likes/create" do |f| %>
        <%= f.submit "Like" %>
      <% end %>
      <a href=<%="/users/id/posts/#{@post.id}/comments/new"%>>Comment</a>
    </div>
    <div class="comments-container">
      <%if @post.comments.empty? %>
        <p>No comments found!</p>
      <% else %>
        <% @post.comments.each do |comment| %>
          <p><%=comment.author.name%>: <%=comment.text%></p>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/users/_user_card.html.erb
<div class="user-card">
  <img src=<%=user.photo%> alt="user-profile" />
  <div class="card-info">
    <h2><%=user.name%></h2>
    <p>Number of posts: <%= user.posts_counter %></p>
  </div>
</div>

app/views/users/index.html.erb
<section class="list-container">
  <h1>Users</h1>
  <div>
    <a href="/users/21/posts/new"> Create Post </a>
  </div>
  <% @users.each do |user| %>
    <%= link_to user_path(user) do %>
      <%= render 'user_card', user: user %>
    <% end %>
  <% end %>
</section>

app/views/users/show.html.erb
<section class="user-profile">
  <h1>User Profile</h1>
  <%= render 'user_card', user: @user %>
  <div class="profile-bio">
    <h3>Bio</h3>
    <p><%= @user.bio.slice(0, 200)... %></p>
  </div>
  <div class="post-card-container">
    <% @user.recent_three.each_with_index do |post, index| %> 
      <%= link_to user_post_path(@user, post) do %>
        <%= render "posts/post_card", post: post, index: index %>
      <% end %> 
    <% end %>
  </div>
    <%= link_to user_posts_path(@user) do %>
      <button class="see-all-btn">See all posts</button>
  <%end %>
</section>